// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "description": "A small, low-opinionated static site generator with sections and items",
  "name": "t2006",
  "version": {
    "dev": 0,
    "major": 0,
    "minor": 4,
    "patch": 0,
    "revision": 5,
    "text": "0.4.0",
    "timestamp": 1715509382
  },
  "stack": {
    "nodejs": {
      "outputFile": [
        "src",
        "cinnabar.js"
      ],
      "package": "t2006"
    }
  }
};
