// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "description": "A small, low-opinionated static site generator for showcasing your projects",
  "name": "t2006",
  "version": {
    "major": 0,
    "minor": 2,
    "patch": 1,
    "revision": 3,
    "text": "0.2.1",
    "timestamp": 1711105111
  },
  "stack": {
    "nodejs": {
      "outputFile": [
        "src",
        "cinnabar.js"
      ],
      "package": "t2006"
    }
  }
};
